### ISSUE TITLE
Dashes in aliases

### ISSUE THREAD

**Issue by xPaw** [github/gemoji#184] opened 2020-08-13 07:53 UTC
There's a couple of aliases that use dashes instead of underscores: `t-rex`, `e-mail`, `non-potable_water`, `-1`.

Discord for example uses underscores for first three, and doesn't have `-1` alias.

In [The Lounge](https://github.com/thelounge/thelounge/pull/4029) typing `:-P` would trigger our auto completion for non-potable_water, so for now I just replaced dashes to underscores (except for `-1`) which should probably be fine.

Any reason for gemoji to keep dashes in these?

**Comment by jobveldhuis** [comment] 2020-08-14 15:26
While this is debatable, I think the choice has been made to follow linguistic convention here. Your three examples would in real life be written as:
- T-rex (or T. Rex, depending on your preference)
- E-mail
- Non-potable water

As demonstrated, the underscore is used by gemoji to replace spaces. I'm not sure if this is done consistently, but it should be. Following linguistic rules does seem like the obvious way to go and thus I would argue we should not alter the dashes in those words.

**Comment by xPaw** [comment] 2020-08-14 15:38
As for e-mail, there's also email alias without dash that has a different emoji variant.

**Comment by jobveldhuis** [comment] 2020-08-14 15:44
While I dislike the fact that gemoji uses both of them for different emoji, linguistically both the spelling of ```e-mail``` and ```email``` are allowed.

There is a possibility to eliminate the dashes from these names and adhere to linguistic standards, but it would include the following changes:
- Change ```t-rex``` to ```dinosaur``` (or a derivative of dinosaur)
- Change ```e-mail``` to ```email``` (or a derivative of email, since it has already been taken by another emoji)
- Change ```non-potable_water``` to ```nonpotable_water```, since American English words allow for the prefix ```non-``` to be written without hyphen.

**Comment by xPaw** [comment] 2020-08-14 16:01
:email: right now is ✉️  which is more of an envelope, and :e-mail: 📧 has the @ symbol.

There's other emojis that use envelope, letter or mail aliases. The current :email: could likely be changed to envelope/letter, and dash removed from e-mail. Emojipedia lists `:envelope:` for it.

**Comment by jobveldhuis** [comment] 2020-08-14 16:14
I agree, this would be a good change and more in style with the symbols of the emoji.

**Comment by mislav** [comment] 2020-08-19 13:03
There is not a super-strong reason why gemoji would keep dashes in these aliases, but I guess the strongest reason right now would be backwards-compatibility. If we removed them from canonical `:emoji:` representations, we would have to add them back as aliases for those emoji to keep compatibility for those who are currently using them.

I don't feel like there is a strong reason to eliminate dashes, however, so they are likely to say. Avoiding emoji collision in another app that supports additional emoticons such as `:-P` is not a strong enough reason in my view; I'm sorry. This feels to me more like a usage problem than a library problem.

**Comment by jobveldhuis** [comment] 2020-08-19 13:50
I cannot say I fully agree with you on the usage issue, @mislav. Not because this is not true (because yes, in the end it is an issue with the way this library is being implemented and, as such, not per se an issue with the library itself), but because I feel like emoji like ```:-p``` are classic emoji that either should be supported by gemoji as an alias (```-p``` should in that case be an alias for ```stuck_out_tongue```) or the naming of emoji in gemoji should be so that they cannot and will not be confused with automcomplete for standard emoji.

Personally I feel like adding aliases for the classic emoji should do the trick, but I am unsure how you feel about this (because this would mean ```-p``` will be marked down as ```:-p:```).

**Comment by xPaw** [comment] 2020-08-19 18:24
@mislav what do you think about the email/envelope emojis?

**Comment by mislav** [comment] 2020-08-20 09:39
@xPaw I wasn't aware of `:email:` vs `:e-mail:` distinction! I'd be fine if `:email:` rendered as 📧 and `:e-mail:` was added as alias for `:email:` (for backwards compatibility). `:envelope:` could be ✉️

**Comment by jobveldhuis** [comment] 2020-08-20 10:02
@mislav I have updated the emoji.json to reflect this change. Please see #185.

**Comment by Superleah66** [comment] 2022-10-11 21:47
> While I dislike the fact that gemoji uses both of them for different emoji, linguistically both the spelling of `e-mail` and `email` are allowed.
> 
> There is a possibility to eliminate the dashes from these names and adhere to linguistic standards, but it would include the following changes:
> 
> * Change `t-rex` to `dinosaur` (or a derivative of dinosaur)
> * Change `e-mail` to `email` (or a derivative of email, because it has already been taken by another emoji)
> * Change `non-potable_water` to `nonpotable_water`, because American English words allow for the prefix `non-` to be written without hyphen.

emoji = Emoji.find_by_alias "musical_note"

Emoji.edit_emoji(emoji) do |char|
  char.add_alias "music"
  char.add_unicode_alias "\u{266b}"
  char.add_tag "notes"
end

Emoji.find_by_alias "music"       #=> emoji
Emoji.find_by_unicode "\u{266b}"  #=> emoji

**Comment by Superleah66** [comment] 2022-10-11 21:51
This version of the Terms of Service is optimized for mobile viewing. To read more information about these terms, visit policies.google.com/terms in your browser.
GOOGLE TERMS OF SERVICE
Effective January 5, 2022

[Country version:](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-country-version) United States

What’s covered in these terms
We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services), and what we expect from you.
These Terms of Service reflect [the way Google’s business works](https://about.google/intl/en_US/how-our-business-works), the laws that apply to our company, and [certain things we’ve always believed to be true](https://www.google.com/about/philosophy.html). As a result, these Terms of Service help define Google’s relationship with you as you interact with our services. For example, these terms include the following topic headings:

[What you can expect from us](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-what-you-expect), which describes how we provide and develop our services
[What we expect from you](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-what-we-expect), which establishes certain rules for using our services
[Content in Google services](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-content), which describes the intellectual property rights to the content you find in our services — whether that content belongs to you, Google, or others
[In case of problems or disagreements](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-problems), which describes other legal rights you have, and what to expect in case someone violates these terms
Understanding these terms is important because, by using our services, you’re agreeing to these terms.

Besides these terms, we also publish a [Privacy Policy](https://policies.google.com/privacy?utm_source=androidsettings). We encourage you to read it to better understand how you can [update, manage, export, and delete your information](https://myaccount.google.com/).

Terms
Service provider
Google [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) are provided by, and you’re contracting with:

Google LLC
organized under the laws of the State of Delaware, USA, and operating under the laws of the USA

1600 Amphitheatre Parkway
Mountain View, California 94043
USA

Age requirements
If you’re under the [age required to manage your own Google Account](https://support.google.com/accounts/answer/1350409), you must have your parent or legal guardian’s permission to use a Google Account. Please have your parent or legal guardian read these terms with you.

If you’re a parent or legal guardian, and you allow your child to use the [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services), then these terms apply to you and you’re responsible for your child’s activity on the services.

Some Google services have additional age requirements as described in their [service-specific additional terms and policies](https://policies.google.com/terms/service-specific?utm_source=androidsettings).

Your relationship with Google
These terms help define the relationship between you and Google. Broadly speaking, we give you permission to use our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) if you agree to follow these terms, which reflect [how Google’s business works and how we earn money](https://about.google/intl/en_US/how-our-business-works). When we speak of “Google,” “we,” “us,” and “our,” we mean Google LLC and its [affiliates](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-affiliates).

What you can expect from us
Provide a broad range of useful services
We provide a broad range of services that are subject to these terms, including:
apps and sites (like Search and Maps)
platforms (like Google Shopping)
integrated services (like Maps embedded in other companies’ apps or sites)
devices (like Google Nest)
Many of these services also include content that you can stream or interact with.

Our services are designed to work together, making it easier for you to move from one activity to the next. For example, if your Calendar event includes an address, you can click on that address and Maps can show you how to get there.

Develop, improve, and update Google services
We’re constantly developing new technologies and features to improve our services. For example, we use artificial intelligence and machine learning to provide you with simultaneous translations, and to better detect and block spam and malware. As part of this continual improvement, we sometimes add or remove features and functionalities, increase or decrease limits to our services, and start offering new services or stop offering old ones. When a service requires or includes downloadable software, that software sometimes updates automatically on your device once a new version or feature is available. Some services let you adjust your automatic update settings.

If we make material changes that negatively impact your use of our services or if we stop offering a service, we’ll provide you with reasonable advance notice, except in urgent situations such as preventing abuse, responding to legal requirements, or addressing security and operability issues. We’ll also provide you with an opportunity to export [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content) from your Google Account using [Google Takeout,](https://takeout.google.com/settings/takeout) subject to applicable law and policies.

What we expect from you
Follow these terms and service-specific additional terms
The permission we give you to use our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) continues as long as you comply with:
these terms
[service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), which could, for example, include things like additional age requirements
You also agree that our [Privacy Policy](https://policies.google.com/privacy?utm_source=androidsettings) applies to your use of our services. Additionally, we provide resources like the [Copyright Help Center](https://support.google.com/legal/topic/4558877), [Safety Center](https://safety.google/), and descriptions of our technologies from our [policies site](https://policies.google.com/technologies?utm_source=androidsettings) to answer common questions and to set expectations about using our services.

Although we give you permission to use our services, we retain any [intellectual property rights](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-intellectual-property-rights) we have in the services.

Respect others
We want to maintain a respectful environment for everyone, which means you must follow these basic rules of conduct:
comply with applicable laws, including export control, sanctions, and human trafficking laws
respect the rights of others, including privacy and intellectual property rights
don’t abuse or harm others or yourself (or threaten or encourage such abuse or harm) — for example, by misleading, defrauding, illegally impersonating, defaming, bullying, harassing, or stalking others
don’t abuse, harm, interfere with, or disrupt the services — for example, by accessing or using them in fraudulent or deceptive ways, introducing malware, or spamming, hacking, or bypassing our systems or protective measures. When we index the web to bring you search results, we respect standard usage restrictions that website owners specify in their websites’ code, so we require the same when others use our services
Our [service-specific additional terms and policies](https://policies.google.com/terms/service-specific?utm_source=androidsettings) provide additional details about appropriate conduct that everyone using those services must follow. If you find that others aren’t following these rules, many of our services allow you to [report abuse](https://support.google.com/groups/answer/81275). If we act on a report of abuse, we also provide the process described in the [Taking action in case of problems](https://policies.google.com/terms/embedded?utm_source=androidsettings#taking-action) section.

Permission to use your content
Some of our services are designed to let you upload, submit, store, send, receive, or share [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content). You have no obligation to provide any content to our services and you’re free to choose the content that you want to provide. If you choose to upload or share content, please make sure you have the necessary rights to do so and that the content is lawful.

License
[Your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content) remains yours, which means that you retain any [intellectual property rights](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-intellectual-property-rights) that you have in your content. For example, you have intellectual property rights in the creative content you make, such as reviews you write. Or you may have the right to share someone else’s creative content if they’ve given you their permission.

We need your permission if your intellectual property rights restrict our use of your content. You provide Google with that permission through this license.

What’s covered
This license covers [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content) if that content is protected by intellectual property rights.

What’s not covered
This license doesn’t affect your privacy rights — it’s only about your intellectual property rights
This license doesn’t cover these types of content:
publicly-available factual information that you provide, such as corrections to the address of a local business. That information doesn’t require a license because it’s considered common knowledge that everyone’s free to use.
feedback that you offer, such as suggestions to improve our services. Feedback is covered in the [Service-related communications](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-service-related-comm) section below.
Scope
This license is:
worldwide, which means it’s valid anywhere in the world
non-exclusive, which means you can license your content to others
royalty-free, which means there are no monetary fees for this license
Rights
This license allows Google to:

host, reproduce, distribute, communicate, and use your content — for example, to save your content on our systems and make it accessible from anywhere you go
publish, publicly perform, or publicly display your content, if you’ve made it visible to others
modify and create derivative works based on your content, such as reformatting or translating it
sublicense these rights to:
other users to allow the services to work as designed, such as enabling you to share photos with people you choose
our contractors who’ve signed agreements with us that are consistent with these terms, only for the limited purposes described in the [Purpose](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-purpose) section below
Purpose
This license is for the limited purpose of:

operating and improving the services, which means allowing the services to work as designed and creating new features and functionalities. This includes using automated systems and algorithms to analyze your content:
for spam, malware, and illegal content
to recognize patterns in data, such as determining when to suggest a new album in Google Photos to keep related photos together
to customize our services for you, such as providing recommendations and personalized search results, content, and ads (which you can change or turn off in [Ads Settings](https://adssettings.google.com/?ref=ps-terms))
This analysis occurs as the content is sent, received, and when it is stored.
using content you’ve shared publicly to promote the services. For example, to promote a Google app, we might quote a review you wrote. Or to promote Google Play, we might show a screenshot of the app you offer in the Play Store.
developing new technologies and services for Google consistent with these terms
Duration
This license lasts for as long as your content is protected by intellectual property rights.

If you remove from our services any content that’s covered by this license, then our systems will stop making that content publicly available in a reasonable amount of time. There are two exceptions:

If you already shared your content with others before removing it. For example, if you shared a photo with a friend who then made a copy of it, or shared it again, then that photo may continue to appear in your friend’s Google Account even after you remove it from your Google Account.
If you make your content available through other companies’ services, it’s possible that search engines, including Google Search, will continue to find and display your content as part of their search results.
Using Google services
Your Google Account
[If you meet these age requirements](https://support.google.com/accounts/answer/1350409) you can [create a Google Account](https://support.google.com/accounts/answer/27441) for your convenience. Some [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) require that you have a Google Account in order to work — for example, to use Gmail, you need a Google Account so that you have a place to send and receive your email.

You’re responsible for what you do with your Google Account, including taking reasonable steps to keep your Google Account secure, and we encourage you to regularly use the [Security Checkup](https://myaccount.google.com/security-checkup).

Using Google services on behalf of an organization or business
Many [organizations](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-organization), such as businesses, non-profits, and schools, take advantage of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services). To use our services on behalf of an organization:
an authorized representative of that organization must agree to these terms
your organization’s administrator may assign a Google Account to you. That administrator might require you to follow additional rules and may be able to access or disable your Google Account.
Service-related communications
To provide you with our services, we sometimes send you service announcements and other information. To learn more about how we communicate with you, see Google’s [Privacy Policy](https://policies.google.com/privacy?utm_source=androidsettings).

If you choose to give us feedback, such as suggestions to improve our services, we may act on your feedback without obligation to you.

Content in Google services
Your content
Some of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) give you the opportunity to make your content publicly available — for example, you might post a product or restaurant review that you wrote, or you might upload a blog post that you created.

See the [Permission to use your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-permission) section for more about your rights in [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content), and how your content is used in our services
See the [Removing your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#toc-removing) section to learn why and how we might remove user-generated content from our services
If you think someone is infringing your [intellectual property rights](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-intellectual-property-rights), you can [send us notice of the infringement](https://support.google.com/legal/answer/3110420) and we’ll take appropriate action. For example, we suspend or close the Google Accounts of repeat [copyright](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-copyright) infringers as described in our [Copyright Help Center](https://support.google.com/legal/topic/4558877).

Google content
Some of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) include content that belongs to Google — for example, many of the visual illustrations you see in Google Maps. You may use Google’s content as allowed by these terms and any [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), but we retain any intellectual property rights that we have in our content. Don’t remove, obscure, or alter any of our branding, logos, or legal notices. If you want to use our branding or logos, please see the [Google Brand Permissions](https://www.google.com/permissions) page.

Other content
Finally, some of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) give you access to content that belongs to other people or [organizations](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-organization) — for example, a store owner’s description of their own business, or a newspaper article displayed in Google News. You may not use this content without that person or organization’s permission, or as otherwise allowed by law. The views expressed in other people or organizations’ content are theirs, and don’t necessarily reflect Google’s views.

Software in Google services
Some of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) include downloadable software. We give you permission to use that software as part of the services.

The license we give you is:
worldwide, which means it’s valid anywhere in the world
non-exclusive, which means that we can license the software to others
royalty-free, which means there are no monetary fees for this license
personal, which means it doesn’t extend to anyone else
non-assignable, which means you’re not allowed to assign the license to anyone else
Some of our services include software that’s offered under open source license terms that we make available to you. Sometimes there are provisions in the open source license that explicitly override parts of these terms, so please be sure to read those licenses.

You may not copy, modify, distribute, sell, or lease any part of our services or software.

In case of problems or disagreements
Warranty disclaimer
We built our reputation on providing useful, reliable services like Google Search and Maps, and we’re continuously improving our services to meet your needs. However, for legal purposes, we offer our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) without [warranties](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-warranty) unless explicitly stated in our [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings). The law requires that we explain this using specific legal language and that we use capital letters to help make sure you see it, as follows:

TO THE EXTENT ALLOWED BY APPLICABLE LAW, WE PROVIDE OUR SERVICES “AS IS” WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. FOR EXAMPLE, WE DON’T MAKE ANY WARRANTIES ABOUT THE CONTENT OR FEATURES OF THE SERVICES, INCLUDING THEIR ACCURACY, RELIABILITY, AVAILABILITY, OR ABILITY TO MEET YOUR NEEDS.

Liabilities
For all users
Both the law and these terms try to strike a balance as to what you or Google can claim from the other in case of problems. That’s why the law allows us to limit certain [liabilities](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-liability) — but not others — under these terms.

These terms only limit our responsibilities as allowed by applicable law. These terms don’t limit liability for gross negligence or willful misconduct.

To the extent allowed by applicable law:
Google is liable only for its breaches of these terms or applicable [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings)
Google isn’t liable for:
loss of profits, revenues, business opportunities, goodwill, or anticipated savings
indirect or consequential losses
punitive damages
Google’s total liability arising out of or relating to these terms is limited to the greater of (1) $200 or (2) the fees paid to use the relevant services in the 12 months before the dispute
For business users and organizations only
If you’re a [business user](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-business-user) or [organization](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-organization):

To the extent allowed by applicable law, you’ll [indemnify](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-indemnify) Google and its directors, officers, employees, and contractors for any third-party legal proceedings (including actions by government authorities) arising out of or relating to your unlawful use of the [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) or violation of these terms or [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings). This indemnity covers any liability or expense arising from claims, losses, damages, judgments, fines, litigation costs, and legal fees.
If you’re legally exempt from certain responsibilities, including [indemnification](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-indemnify), then those responsibilities don’t apply to you under these terms. For example, the United Nations enjoys certain immunities from legal obligations and these terms don’t override those immunities.
Taking action in case of problems
Before taking action as described below, we’ll provide you with advance notice when reasonably possible, describe the reason for our action, and give you an opportunity to fix the problem, unless doing so would:

cause harm or [liability](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-liability) to a user, third party, or Google
violate the law or a legal enforcement authority’s order
compromise an investigation
compromise the operation, integrity, or security of our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services)
Removing your content
If any of [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content) (1) breaches these terms, [service-specific additional terms or policies](https://policies.google.com/terms/service-specific?utm_source=androidsettings), (2) violates applicable law, or (3) could harm our users, third parties, or Google, then we reserve the right to take down some or all of that content in accordance with applicable law. Examples include child pornography, content that facilitates human trafficking or harassment, terrorist content, and content that infringes someone else’s [intellectual property rights](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-intellectual-property-rights).

Suspending or terminating your access to Google services
Google reserves the right to suspend or terminate your access to the services or delete your Google Account if any of these things happen:

you materially or repeatedly breach these terms, [service-specific additional terms or policies](https://policies.google.com/terms/service-specific?utm_source=androidsettings)
we’re required to do so to comply with a legal requirement or a court order
your conduct causes harm or [liability](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-liability) to a user, third party, or Google — for example, by hacking, phishing, harassing, spamming, misleading others, or scraping content that doesn’t belong to you
For more information about why we disable accounts and what happens when we do, see this [Help Center page](https://support.google.com/accounts/answer/40695). If you believe your Google Account has been suspended or terminated in error, [you can appeal](https://support.google.com/accounts/answer/40695).

Of course, you’re always free to stop using our services at any time. If you do stop using a service, we’d [appreciate knowing why](https://www.google.com/tools/feedback) so that we can continue improving our services.

Settling disputes, governing law, and courts
For information about how to contact Google, please visit our [contact page](https://www.google.com/contact).

California law will govern all disputes arising out of or relating to these terms, [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), or any related [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services), regardless of conflict of laws rules. These disputes will be resolved exclusively in the federal or state courts of Santa Clara County, California, USA, and you and Google consent to personal jurisdiction in those courts.

About these terms
By law, you have certain rights that can’t be limited by a contract like these terms of service. These terms are in no way intended to restrict those rights.

These terms describe the relationship between you and Google. They don’t create any legal rights for other people or [organizations](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-organization), even if others benefit from that relationship under these terms.

We want to make these terms easy to understand, so we’ve used examples from our [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services). But not all services mentioned may be available in your country.

If these terms conflict with the [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), the additional terms will govern for that service.

If it turns out that a particular term is not valid or enforceable, this will not affect any other terms.

If you don’t follow these terms or the [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), and we don’t take action right away, that doesn’t mean we’re giving up any rights that we may have, such as taking action in the future.

We may update these terms and [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings) (1) to reflect changes in our services or how we do business — for example, when we add new services, features, technologies, pricing, or benefits (or remove old ones), (2) for legal, regulatory, or security reasons, or (3) to prevent abuse or harm.

If we materially change these terms or [service-specific additional terms](https://policies.google.com/terms/service-specific?utm_source=androidsettings), we’ll provide you with reasonable advance notice and the opportunity to review the changes, except (1) when we launch a new service or feature, or (2) in urgent situations, such as preventing ongoing abuse or responding to legal requirements. If you don’t agree to the new terms, you should remove [your content](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-your-content) and stop using the services. You can also end your relationship with us at any time by closing your Google Account.

affiliate
An entity that belongs to the Google group of companies, which means Google LLC and its subsidiaries, including the following companies that provide consumer services in the EU: Google Ireland Limited, Google Commerce Limited, and Google Dialer Inc.

business user
An individual or entity who is not a consumer (see consumer).

consumer
An individual who uses Google services for personal, non-commercial purposes outside of their trade, business, craft, or profession. (See business user)

copyright
A legal right that allows the creator of an original work (such as a blog post, photo, or video) to decide if and how that original work may be used by others, subject to certain limitations and exceptions (such as “fair use” and “fair dealing”).

country version
If you have a Google Account, we associate your account with a country (or territory) so that we can determine:

the Google [affiliate](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-affiliates) that provides the [services](https://policies.google.com/terms/embedded?utm_source=androidsettings#footnote-services) to you and that processes your information as you use the services
the version of the terms that govern our relationship
When you’re signed out, your country version is determined by the location where you’re using Google services. If you have an account, you can [sign in](https://accounts.google.com/ServiceLogin?hl=en-US&continue=https://policies.google.com/terms/embedded?utm_source%3Dandroidsettings) and view these terms to see the country associated with it.

disclaimer
A statement that limits someone’s legal responsibilities.

indemnify or indemnity
An individual or organization’s contractual obligation to compensate the losses suffered by another individual or organization from legal proceedings such as lawsuits.

intellectual property rights (IP rights)
Rights over the creations of a person’s mind, such as inventions (patent rights); literary and artistic works (copyright); designs (design rights); and symbols, names, and images used in commerce (trademarks). IP rights may belong to you, another individual, or an organization.

liability
Losses from any type of legal claim, whether the claim is based on a contract, tort (including negligence), or other reason, and whether or not those losses could have been reasonably anticipated or foreseen.

organization
A legal entity (such as a corporation, non-profit, or school) and not an individual person.

services
The Google services that are subject to these terms are the products and services listed at [https://policies.google.com/terms/service-specific](https://policies.google.com/terms/service-specific?utm_source=androidsettings), including:

apps and sites (like Search and Maps)
platforms (like Google Shopping)
integrated services (like Maps embedded in other companies’ apps or sites)
devices and other goods (like Google Nest)
Many of these services also include content that you can stream or interact with.

trademark
Symbols, names, and images used in commerce that are capable of distinguishing the goods or services of one individual or organization from those of another.

warranty
An assurance that a product or service will perform to a certain standard.

your content
Things that you create, upload, submit, store, send, receive, or share using our services, such as:

Docs, Sheets, and Slides you create
blog posts you upload through Blogger
reviews you submit through Maps
videos you store in Drive
emails you send and receive through Gmail
pictures you share with friends through Photos
travel itineraries that you share with Google

**Comment by mislav** [comment] 2022-11-15 18:03
Closing since we've addressed the `e-mail` vs `email` vs `envelope` situation., but I do not feel like `t-rex` or `non-potable_water` represent any problem, and we want to keep them for backwards compatibility.

**Closed by mislav** 2022-11-15 18:03 UTC
