### ISSUE TITLE
Update for latest iOS version

### ISSUE THREAD

**Issue by LeTanThanh** [github/gemoji#138] opened 2018-01-23 08:32 UTC
I see that the current latest ios_version is 10.2, can you update emoji for iOS 11.
My project is using iOS 11 and i foudn that some emoji is not supported.
What about emoji for android, I see that some emoji for android isn't supported.

**Comment by Crissov** [comment] 2018-02-09 10:22
This is a duplicate of #134. Both are asking for Unicode 10.0 and Emoji 5.0 support, which has been added to iOS 11.1 in late October 2017 but was already published in June 2017.

**Comment by mislav** [comment] 2018-02-09 11:15
Closing as duplicate

**Closed by mislav** 2018-02-09 11:15 UTC
